name: PR Event Listener

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]
  push:

jobs:
  process_pr_events:
    runs-on: ubuntu-latest

    steps:
      - name: Extract event details
        run: |
          echo "EVENT_PAYLOAD=$(jq -c . < $GITHUB_EVENT_PATH)" >> $GITHUB_ENV

      - name: Call External API
        run: |
          curl -X POST https://firstly-worthy-chamois.ngrok-free.app/github-webhook \
          -H "Content-Type: application/json" \
          -d "$EVENT_PAYLOAD"
